### PR TITLE
Initial porting to mbed cores (Nano33BLE)

### PR DESCRIPTION
**Pull request by facchinm**

### CODE REVIEW

**Comment by SravyaAmirisetti** [comment]
I tested on Windows 10 and it works fine.

Thanks.

**Comment by RudolfAtHome** [comment]
OK - with this extensions and changes the library Servo works - but not as expected.
I have a sketch that writes each 20 ms a new value to the Servo with Servo.write(...). The goal is an acceleration and deceleration and a speed control for the servo. 
 - This works fine on Nano Classic and Nano Every. 
 - On my Nano 33 BLE (with the new Servo lib) the Servo gets no signals (!) during the active movement part of my sketch. At the end the servo goes with maximum speed to the desired position.
Serco_embed
The signals from Salea logic analyser:
 **- Servo**: Signals at the Servo pin - generated by the Servo library
 **- Update**: At each transition the Servo.write(...) gives a new value (20 ms) - too often??
 **- Move active**: Rising starts acceleration, falling shows the end of moment after deceleration

**Comment by facchinm** [comment]
Hi @RudolfAtHome , 20ms may be a bit too often since it matches the internal update routine. You may try to change this line (https://github.com/arduino-libraries/Servo/pull/32/files#diff-6e8f8b6f65fd0d27263c4071ec5ebbceR24) to `0.1f` and check if it works as expected. 
Anyway, I think relaxing a bit your update routine could work better :wink:

**Comment by RudolfAtHome** [comment]
Hello Martino,
you are right, 20 ms is too often. I have changed my update period time to 50 ms (-> 20 writes / second) and it works. 
Thank you for your helpful work!
With regards, Rudolf.

**Comment by Netguykb** [comment]
After installing new servo driver 1.1.6 using a Nano 33 BLE "Sweep" Example I get the following error:

Arduino: 1.8.10 (Mac OS X), Board: "Arduino Nano, ATmega328P"

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/kellybrady/Library/Arduino15/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/kellybrady/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/kellybrady/Documents/Arduino/libraries -fqbn=arduino:avr:nano:cpu=atmega328 -vid-pid=0X2341_0X805A -ide-version=10810 -build-path /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053 -warnings=none -build-cache /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_cache_652848 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.arduinoOTA-1.3.0.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -verbose /Users/kellybrady/Documents/Arduino/libraries/Servo/examples/Sweep/Sweep.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/kellybrady/Library/Arduino15/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/kellybrady/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/kellybrady/Documents/Arduino/libraries -fqbn=arduino:avr:nano:cpu=atmega328 -vid-pid=0X2341_0X805A -ide-version=10810 -build-path /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053 -warnings=none -build-cache /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_cache_652848 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.arduinoOTA-1.3.0.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -verbose /Users/kellybrady/Documents/Arduino/libraries/Servo/examples/Sweep/Sweep.ino
Using board 'nano' from platform in folder: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr
Using core 'arduino' from platform in folder: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr
Detecting libraries used...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/sketch/Sweep.ino.cpp -o /dev/null
Alternatives for Servo.h: [Servo@1.1.5 Servo@1.1.6]
ResolveLibrary(Servo.h)
  -> candidates: [Servo@1.1.5 Servo@1.1.6]
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/sketch/Sweep.ino.cpp -o /dev/null
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /Users/kellybrady/Documents/Arduino/libraries/Servo/src/avr/Servo.cpp -o /dev/null
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /Users/kellybrady/Documents/Arduino/libraries/Servo/src/mbed/Servo.cpp -o /dev/null
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /Users/kellybrady/Documents/Arduino/libraries/Servo/src/megaavr/Servo.cpp -o /dev/null
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /Users/kellybrady/Documents/Arduino/libraries/Servo/src/nrf52/Servo.cpp -o /dev/null
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /Users/kellybrady/Documents/Arduino/libraries/Servo/src/sam/Servo.cpp -o /dev/null
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /Users/kellybrady/Documents/Arduino/libraries/Servo/src/samd/Servo.cpp -o /dev/null
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /Users/kellybrady/Documents/Arduino/libraries/Servo/src/stm32f4/Servo.cpp -o /dev/null
Generating function prototypes...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/sketch/Sweep.ino.cpp -o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/preproc/ctags_target_for_gcc_minus_e.cpp
/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/preproc/ctags_target_for_gcc_minus_e.cpp
Compiling sketch...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs -I/Users/kellybrady/Documents/Arduino/libraries/Servo/src /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/sketch/Sweep.ino.cpp -o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/sketch/Sweep.ino.cpp.o
Compiling libraries...
Compiling library "Servo"
Using previously compiled file: /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/avr/Servo.cpp.o
Using previously compiled file: /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/mbed/Servo.cpp.o
Using previously compiled file: /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/megaavr/Servo.cpp.o
Using previously compiled file: /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/nrf52/Servo.cpp.o
Using previously compiled file: /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/sam/Servo.cpp.o
Using previously compiled file: /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/samd/Servo.cpp.o
Using previously compiled file: /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/stm32f4/Servo.cpp.o
Compiling core...
Using precompiled core: /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_cache_652848/core/core_arduino_avr_nano_cpu_atmega328_51f02b7210b938436b779d1c032618e1.a
Linking everything together...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/Sweep.ino.elf /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/sketch/Sweep.ino.cpp.o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/avr/Servo.cpp.o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/mbed/Servo.cpp.o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/megaavr/Servo.cpp.o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/nrf52/Servo.cpp.o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/sam/Servo.cpp.o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/samd/Servo.cpp.o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/libraries/Servo/stm32f4/Servo.cpp.o /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/../arduino_cache_652848/core/core_arduino_avr_nano_cpu_atmega328_51f02b7210b938436b779d1c032618e1.a -L/var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053 -lm
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/Sweep.ino.elf /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/Sweep.ino.eep
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/Sweep.ino.elf /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/Sweep.ino.hex
Multiple libraries were found for "Servo.h"
 Used: /Users/kellybrady/Documents/Arduino/libraries/Servo
 Not used: /Applications/Arduino.app/Contents/Java/libraries/Servo
Using library Servo at version 1.1.6 in folder: /Users/kellybrady/Documents/Arduino/libraries/Servo 
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-size -A /var/folders/mp/pzjnhqp10zl_qwvtp936qsmm0000gn/T/arduino_build_599053/Sweep.ino.elf
Sketch uses 2128 bytes (6%) of program storage space. Maximum is 30720 bytes.
Global variables use 52 bytes (2%) of dynamic memory, leaving 1996 bytes for local variables. Maximum is 2048 bytes.
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x35
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x36
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x0d
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x0a
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x35
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x37
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x0d
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x0a
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x35
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x37
An error occurred while uploading the sketch

**Comment by per1234** [comment]
@Netguykb this is an upload error. It has nothing to do with the Servo library. 

If you haven't already done so, please create a new thread in the appropriate section of the Arduino forum (http://forum.arduino.cc/). I'm sure we'll be able to help you with the problem over there.

**Comment by Netguykb** [comment]
ok thanks

**Comment by facchinm** [comment]
@Netguykb you are compiling for ` "Arduino Nano, ATmega328P"` while you should select `Arduino NANO 33 BLE` from the menu (after downloading the appropriate core via board manager)

**Comment by Netguykb** [comment]
That worked. Thanks!!

**Pull request merged**
