### PR TITLE
Add support for STM32 boards

### PR DESCRIPTION
**Pull request by fprwi6labs**
Please add support for [STM32 boards](https://github.com/stm32duino/Arduino_Core_STM32).

### CODE REVIEW

**Comment by fpistm** [comment]
Hi,
is there any chance to have this PR merged?

**Comment by fpistm** [comment]
Hi @facchinm ,
did you missed this one also ? ;)

**Comment by fpistm** [comment]
Hi @facchinm  
any new on this ?
Thanks in advance

**Comment by facchinm** [comment]
Hi @fpistm ,
I'll be glad to merge it after the rebase! Sorry for the late response

**Comment by fpistm** [comment]
I will do the rebase and a new PR as @fprwi6labs do not working anymore on STM core.

**Comment by fpistm** [comment]
Hi @facchinm 
you can close this PR as it is no more in line with the STM32 core.
Thanks.

**Comment by fpistm** [comment]
Hi @facchinm
you can close this PR as it is no more in line with the STM32 core.
we provide it as a buitin library.
Thanks

**Pull request closed without merging**
